[manager]
prepend_keymap = [
  { on = "w", run = "close", desc = "Close the current tab" },
  { on = "L", run = "tab_switch --relative 1", desc = "Switch to the next tab" },
  { on = "H", run = "tab_switch --relative -1", desc = "Switch to the previous tab" },
]
